export * from "./actor.interface";
export * from "./credits.interface"
export * from "./crew_member.interface";
export * from "./genre.interface";
export * from "./genres.interface";
export * from "./movie.details.interface";
export * from "./movie.interface";
export * from "./page.interface";
export * from "./person.details.interface";
export * from "./video.interface";
export * from "./video.page.interface";
